### ISSUE TITLE
innertext can't be changed

### ISSUE THREAD

**Issue by philipheimboeck** [voku/simple_html_dom#14]
I think there is an error in the `SimpleHtmlDom::replaceChild` method.
I always get a `\RuntimeException` when I try to change the innertext.

My code looks like this:

```php
$html = HtmlDomParser::str_get_html($html);
$elements = $html->find('head', -1);
foreach($elements as $element_to_modify) {
    $element_to_modify->innertText .= $some_additional_content;
}
```

Inside of the `SimpleHtmlDom::replaceChild` method there is the following check:

```php
if ($this->normalizeStringForComparision($newDocument->outerText()) != $this->normalizeStringForComparision($string)) {
    throw new RuntimeException('Not valid HTML fragment');
}
```

Now as I am trying to change the innertext `$newDocument->outerText()` returns something different than the `$string` variable.
In my case it looks like this.

```php
$newDocument->outerText() == "<head><meta ....> ....</head>"
$string == "<meta ...> ...."
```

**Comment by voku** [comment]
The problem was that "DomDocument" tries to fix invalid html, so that it can handle it and so, it added "<head>...</head>" around your input. 

I fixed the issue, by removing the magically added html and I added some tests here, hope this helps you: https://github.com/voku/simple_html_dom/commit/a42c8683c876a1cd2f6ef15ddcd408e34bc28950#diff-f9e35e3ee28495a595a36e0f7a4ae154R338
