### ISSUE TITLE
Append or prepend elements

### ISSUE THREAD

**Issue by Thanty** [voku/simple_html_dom#40]
#### What is this feature about (expected vs actual behaviour)?

It was possible in "original" Simple Html Dom to append or prepend html data using outerhtml attribute like this:

```
$d = new voku\helper\HtmlDomParser;
$d->loadHtml("<p>p1</p><p>p2</p>");
$p = $d->find('p', 0);
$p->outerhtml .= '<div>outer</div>';
``` 
Expected result: `<p>p1</p><div>outer</div><p>p2</p>`

Now when I'm trying to do this, result paragraph html is equal to paragraph innerhtml, all tags are stripped.

Actual result: `p1<p>p2</p>`

It would be great to restore initial behaviour or create methods like `append()`, `prepend()`.

Thanks in advance!

**Comment by voku** [comment]
Fixed in version 4.7.9

I fixed the function, because it was not correct, so there are no new method. The problem was again the DomDocument itself, it adds doctype, ```<html>```-, ```<p>```-tags, ... automatically, but we want to add e.g. ```<div>outer</div>``` and not ```<html><body><div>outer</div></body></html>``` into the existing html, so I tried to move the inner html to the top. And here comes the next problem, if the first tag was already a ```<p>``` tag in the source html. -> https://github.com/voku/simple_html_dom/commit/d0a3e31f43ddc2add340d3670da13b582cbdc597#diff-1e163f80dacdd100af6446e4282fa7caL809
